# TODO: Define structure and write Schema
scorer:
  in_memory_database: 'metadata.db'
  nr_files_update: 3

feeder:
  batch_size: 100
  input_file: '/data/train/train_mini.csv'
  interval_length: 10

kafka:
  topic: 'test'
  bootstrap_servers:
    - 'kafka:29092'
