dataset: 
  name: SplitCIFAR10
  batch_size: 64
  collapse_targets: True

model:
  name: smallconv
  in_channels: 3
  num_classes: 10
  dropout: 0.2

lr: 0.001
epochs: 8
trainer: 
  name: naiveTaskBasedTrainer
  memory_buffer_size: 10
