dataset: 
  name: SplitCIFAR10
  batch_size: 64
  collapse_targets: False

model:
  name: smallconv
  in_channels: 3
  num_classes: 10
  dropout: 0.2

lr: 0.001
epochs: 2
trainer: 
  name: uniformSamplingTaskBasedTrainer
  memory_buffer_size: 12
  get_grad_error: True
