dataset: 
  name: SplitMNIST
  batch_size: 256
  collapse_targets: True

model:
  name: vanilla
  widths: [784, 800, 2]

lr: 0.001
epochs: 5
trainer: 
  name: uniformSamplingTaskBasedTrainer
  memory_buffer_size: 10