dataset: 
  name: SplitMNIST
  batch_size: 256
  collapse_targets: False

model:
  name: vanilla
  widths: [784, 800, 10]

lr: 0.001
epochs: 2
trainer: 
  name: uniformSamplingTaskBasedTrainer
  memory_buffer_size: 12